export const snackBarMessages = {
	instructions: "Instructions were sent to your email",
	signIn: "Successfully logged in",
	signUp: "Successfully signed up",
	signOut: "Successfully signed out",
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< dev
	passRecovery: "The password was successfully changed",
	sessionExpired: "The session expired. Please, login again.",
	articleCreated: "The article was successfully published"
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
	passRecovery: "The password was successfully changed",
	addComment: "Сomment successfully published"
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> feat/924-create-comments
};
